title: Welcome to my blog
author: Gxiang
email:2865795167@qq.com
description: > # this means to ignore newlines until "baseurl:"
  An interesting person 

# social links
github_username:  A-Insect # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
